host: localhost
port: 8081
providers:
  supported:
    - id: github
      client_secret: GITHUB_SECRET
    - id: google
      client_secret: GOOGLE_SECRET
  other:
    - id: custom
      client_secret: CUSTOM_CLIENT_SECRET
      token_endpoint: https://example.com/oauth2/authorize