name: CI Worker (Svelte)
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      contents: write
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd web 
          npm ci
          npm run build
      - name: Git Auto Commit Svelte Build
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "chore: build svelte frontend"
          commit_user_name: "actions[svelte]"




